import React, { useState } from 'react';
import { Calendar, Save, Plus, Flame, Utensils, Target, Clock, Dumbbell, Droplets, Sparkles } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Modal } from '../components/ui/Modal';
import { useToast } from '../hooks/useToast';
import { DAYS, MEAL_TYPES } from '../data/constants';
import './MealPlanner.css';

export const MealPlanner = ({ profile, plan, API_BASE, token, setActivePlan }) => {
  const { addToast } = useToast();
  const [selectedMeal, setSelectedMeal] = useState(null); // { name, day, type }
  const [generatedRecipe, setGeneratedRecipe] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const todayIdx = new Date().getDay() === 0 ? 6 : new Date().getDay() - 1;

  const handleMealClick = (meal, day, label, key) => {
    setSelectedMeal({ 
      name: meal?.name || '', 
      kcal: meal?.kcal || '', 
      tag: meal?.tag || 'healthy',
      day, 
      typeLabel: label, 
      typeKey: key,
      isNew: !meal
    });
    setGeneratedRecipe(null);
  };

  const updatePlan = async (updatedPlanData) => {
    try {
      const res = await fetch(`${API_BASE}/generate`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ plan: updatedPlanData })
      });
      if (!res.ok) throw new Error('Failed to update plan');
      const data = await res.json();
      setActivePlan(data);
      addToast('Plan Updated', 'Your meal plan has been saved.', 'success');
    } catch (err) {
      addToast('Update Failed', err.message, 'error');
    }
  };

  const saveMealEdit = () => {
    const updatedPlan = { ...plan };
    if (!updatedPlan[selectedMeal.day]) updatedPlan[selectedMeal.day] = {};
    
    updatedPlan[selectedMeal.day][selectedMeal.typeKey] = {
      name: selectedMeal.name,
      kcal: parseInt(selectedMeal.kcal) || 0,
      tag: selectedMeal.tag
    };
    updatePlan(updatedPlan);
    setSelectedMeal(null);
  };

  const deleteMeal = () => {
    const updatedPlan = { ...plan };
    if (updatedPlan[selectedMeal.day]) {
      delete updatedPlan[selectedMeal.day][selectedMeal.typeKey];
    }
    updatePlan(updatedPlan);
    setSelectedMeal(null);
  };

  const generateRecipe = async (mealName) => {
    setIsGenerating(true);
    try {
      const FASTAPI_BASE = import.meta.env.VITE_FASTAPI_URL || 'http://localhost:8000';
      const res = await fetch(`${FASTAPI_BASE}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: [{ role: 'user', content: `Can you give me a simple recipe for ${mealName} including ingredients and short instructions?` }] })
      });
      if (!res.ok) throw new Error('AI Error');
      const data = await res.json();
      setGeneratedRecipe(data.response);
    } catch {
      addToast('Error', 'Could not generate recipe. Is the AI running?', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  const regenerateMeal = async () => {
    setIsGenerating(true);
    try {
      const FASTAPI_BASE = import.meta.env.VITE_FASTAPI_URL || 'http://localhost:8000';
      const res = await fetch(`${FASTAPI_BASE}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ messages: [{ role: 'user', content: `Suggest a single, different ${selectedMeal.typeLabel} under 600 calories. Return ONLY JSON like {"name": "...", "kcal": 450, "tag": "healthy"}` }] })
      });
      const data = await res.json();
      try {
        const parsed = JSON.parse(data.response.replace(/```json|```/g, '').trim());
        setSelectedMeal({ ...selectedMeal, name: parsed.name, kcal: parsed.kcal, tag: parsed.tag });
        addToast('Success', 'AI generated a new meal!', 'success');
      } catch (e) {
        addToast('Error', 'AI returned invalid format. Try again.', 'warning');
      }
    } catch {
      addToast('Error', 'Could not reach AI.', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="page-container animate-fade-in">
      <div className="page-header planner-header">
        <div>
          <h1 className="page-title">Meal Planner</h1>
          <p className="page-subtitle">Your personalized {profile?.dietType || 'balanced'} meal plan generated by AI.</p>
        </div>
      </div>

      <Card className="planner-card">
        <div className="planner-grid-wrapper">
          <div className="planner-grid">
            {/* Header Row */}
            <div className="planner-header-row">
              <div className="planner-corner-cell"></div>
              {DAYS.map((day, di) => (
                <div key={day} className={`planner-day-header ${di === todayIdx ? 'today' : ''}`}>
                  <span className="day-name">{day}</span>
                  {di === todayIdx && <div className="today-dot" />}
                  <div className="day-total-cals">
                    {Object.values(plan[day] || {}).reduce((sum, m) => sum + (m?.kcal || 0), 0)} kcal
                  </div>
                </div>
              ))}
            </div>

            {/* Meal Rows */}
            {MEAL_TYPES.map(({ key, label, icon: Icon }) => (
              <div key={key} className="planner-meal-row">
                <div className="planner-row-label">
                  <Icon size={18} />
                  <span>{label}</span>
                </div>
                
                {DAYS.map((day, di) => {
                  const meal = plan[day]?.[key];
                  const isToday = di === todayIdx;
                  
                  return (
                    <div 
                      key={`${day}-${key}`} 
                      className={`planner-cell ${isToday ? 'today-cell' : ''} ${!meal ? 'empty-cell' : ''}`}
                      onClick={() => handleMealClick(meal, day, label, key)}
                    >
                      {meal ? (
                        <div className="planner-meal-content">
                          <div className="planner-meal-name">{meal.name}</div>
                          <div className="planner-meal-meta">
                            <span className="planner-meal-kcal"><Flame size={12} /> {meal.kcal}</span>
                            {meal.tag && (
                              <Badge 
                                variant={meal.tag === 'healthy' ? 'success' : meal.tag === 'keto' ? 'warning' : meal.tag === 'vegan' ? 'info' : 'default'}
                                size="sm"
                              >
                                {meal.tag}
                              </Badge>
                            )}
                          </div>
                        </div>
                      ) : (
                        <div className="planner-cell-add">
                          <Plus size={20} />
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            ))}
          </div>
        </div>
      </Card>

      {/* Recipe Modal */}
      <Modal 
        isOpen={!!selectedMeal} 
        onClose={() => setSelectedMeal(null)}
        title={`${selectedMeal?.typeLabel} - ${selectedMeal?.day}`}
        size="md"
        footer={
          <div style={{display: 'flex', gap: '8px', width: '100%', justifyContent: 'space-between'}}>
            {!selectedMeal?.isNew && (
              <Button variant="outline-destructive" onClick={deleteMeal}>Delete</Button>
            )}
            <div style={{display: 'flex', gap: '8px', marginLeft: 'auto'}}>
              <Button variant="ghost" onClick={() => setSelectedMeal(null)}>Cancel</Button>
              <Button onClick={saveMealEdit}><Save size={16} style={{marginRight: 8}}/> Save Changes</Button>
            </div>
          </div>
        }
      >
        {selectedMeal && (
          <div className="recipe-modal-content">
            <div style={{display: 'flex', flexDirection: 'column', gap: '16px', marginBottom: '24px'}}>
              <div>
                <label style={{display: 'block', fontSize: '13px', color: 'var(--muted)', marginBottom: '4px'}}>Meal Name</label>
                <input 
                  type="text" 
                  value={selectedMeal.name}
                  onChange={(e) => setSelectedMeal({...selectedMeal, name: e.target.value})}
                  style={{width: '100%', padding: '8px 12px', borderRadius: '8px', border: '1px solid var(--border)', background: 'var(--input-bg)', color: 'var(--foreground)'}}
                />
              </div>
              <div style={{display: 'flex', gap: '16px'}}>
                <div style={{flex: 1}}>
                  <label style={{display: 'block', fontSize: '13px', color: 'var(--muted)', marginBottom: '4px'}}>Calories</label>
                  <input 
                    type="number" 
                    value={selectedMeal.kcal}
                    onChange={(e) => setSelectedMeal({...selectedMeal, kcal: e.target.value})}
                    style={{width: '100%', padding: '8px 12px', borderRadius: '8px', border: '1px solid var(--border)', background: 'var(--input-bg)', color: 'var(--foreground)'}}
                  />
                </div>
                <div style={{flex: 1}}>
                  <label style={{display: 'block', fontSize: '13px', color: 'var(--muted)', marginBottom: '4px'}}>Diet Tag</label>
                  <input 
                    type="text" 
                    value={selectedMeal.tag}
                    onChange={(e) => setSelectedMeal({...selectedMeal, tag: e.target.value})}
                    style={{width: '100%', padding: '8px 12px', borderRadius: '8px', border: '1px solid var(--border)', background: 'var(--input-bg)', color: 'var(--foreground)'}}
                  />
                </div>
              </div>
              
              <Button variant="secondary" onClick={regenerateMeal} disabled={isGenerating} style={{marginTop: '8px'}}>
                <Sparkles size={16} style={{marginRight: 8}} />
                {isGenerating ? 'AI is Thinking...' : 'Regenerate this Meal with AI'}
              </Button>
            </div>

            {!selectedMeal.isNew && (
              <>
                <hr style={{border: 0, borderTop: '1px solid var(--border)', margin: '16px 0'}} />
                {generatedRecipe ? (
                  <div className="recipe-generated">
                    <div className="recipe-section" style={{ whiteSpace: 'pre-wrap', lineHeight: '1.5', color: 'var(--foreground-secondary)' }}>
                      {generatedRecipe}
                    </div>
                  </div>
                ) : (
                  <div className="recipe-missing">
                    <p>Want a detailed recipe for this?</p>
                    <Button 
                      onClick={() => generateRecipe(selectedMeal.name)} 
                      disabled={isGenerating}
                      style={{ marginTop: '1rem' }}
                    >
                      <Sparkles size={16} style={{ marginRight: 8 }} />
                      {isGenerating ? 'Asking AI...' : 'Ask AI for Recipe'}
                    </Button>
                  </div>
                )}
              </>
            )}
          </div>
        )}
      </Modal>
    </div>
  );
};
